variable "resource_group_name" {}
variable "location" {}
variable "azurefw_name" {}
variable "azurefw_vnet_name" {}
variable "azurefw_addr_prefix" {}
variable "law_id" {}
variable "azfw_diag_name" {}
variable "region1_mlw_spk_ip_g_id" {}
variable "region1_hub_ip_g_id" {}